name: nextflow-scrnaseq
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - nextflow
  - star>=2.7.10b
  - fastqc
  - trim-galore
  - multiqc
  - parallel
  - r-base
  - r-seurat
  - r-soupx
  - r-here
  - bioconductor-dropletutils
  - bioconductor-glmgampoi
  - scvi-tools
  - bbknn
  - scib
  - numpy
  - pandas
  - matplotlib
  - rpy2
  - anndata2ri