name: nextflow-metaG
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python
  - nextflow
  - git>=2.38
  - fastqc
  - trim-galore
  - multiqc
  - parallel
  - eclarke::komplexity
  - bioconda::bbmap
  - bioconda::bowtie2
  - bioconda::kraken2
  - bioconda::bracken
  - bioconda::humann
  - bioconda::diamond