name: nextflow-metaG
channels:
  - conda-forge
  - bioconda
  - eclarke
  - defaults
dependencies:
  - python
  - nextflow
  - git>=2.38
  - fastqc
  - trim-galore
  - multiqc
  - parallel
  - eclarke::komplexity
  - bioconda::bbmap
  - bowtie2
  - kraken2
  - bracken
  - humann